//Course: I-BIX-PYT-25-Applied Bioinformatics
//Project Title: Gene Model Visualisation Tool
//Author: Ajin Ajayan Eazhava
//Student ID: 481704
//Date: 21-11-2025


import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ajina
 */
public class MainFrame extends javax.swing.JFrame {
    ArrayList<String[]> gtfData = new ArrayList<>();
    ArrayList<String> geneNames = new ArrayList<>();
    HashMap<String, String> fastaMap = new HashMap<>();
    String genomeSequence = "";
    HashMap<String, String> geneToScaffold = new HashMap<>();
    
    //Sequence Wrapping
    private String wrapSequence(String seq, int lineLength) {
    StringBuilder sb = new StringBuilder();

    for (int i = 0; i < seq.length(); i += lineLength) {
        int end = Math.min(i + lineLength, seq.length());
        sb.append(seq.substring(i, end)).append("\n");
    }

    return sb.toString();
    }
    
    


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gtfTable = new javax.swing.JTable();
        ComputeStatsButton = new javax.swing.JButton();
        HighlightExonsButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        geneList = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        fastaArea = new javax.swing.JTextArea();
        genePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openGTF = new javax.swing.JMenuItem();
        openFASTA = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gtfTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gtfTable);

        ComputeStatsButton.setText("Compute Stats");
        ComputeStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeStatsButtonActionPerformed(evt);
            }
        });

        HighlightExonsButton.setText("Highlight Exons");
        HighlightExonsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighlightExonsButtonActionPerformed(evt);
            }
        });

        drawButton.setText("Visualise Gene");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        geneList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneListActionPerformed(evt);
            }
        });

        fastaArea.setColumns(20);
        fastaArea.setLineWrap(true);
        fastaArea.setRows(5);
        fastaArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(fastaArea);

        genePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        genePanel.setPreferredSize(new java.awt.Dimension(700, 200));

        javax.swing.GroupLayout genePanelLayout = new javax.swing.GroupLayout(genePanel);
        genePanel.setLayout(genePanelLayout);
        genePanelLayout.setHorizontalGroup(
            genePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        genePanelLayout.setVerticalGroup(
            genePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jLabel1.setText("Gene List");

        jMenu1.setText("File");

        openGTF.setText("Open GTF");
        openGTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openGTFActionPerformed(evt);
            }
        });
        jMenu1.add(openGTF);

        openFASTA.setText("Open FASTA");
        openFASTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFASTAActionPerformed(evt);
            }
        });
        jMenu1.add(openFASTA);

        exitMenu.setText("Exit");
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(geneList, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addComponent(genePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(ComputeStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(drawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HighlightExonsButton)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(geneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComputeStatsButton)
                            .addComponent(drawButton)
                            .addComponent(HighlightExonsButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openGTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openGTFActionPerformed
        // Uses FileDialog to select a GTF. 
        FileDialog dialog = new FileDialog(this,"Open GTF File", FileDialog.LOAD);
        dialog.setVisible(true);
        
        String folder = dialog.getDirectory();
        String file = dialog.getFile();
        
        if (file == null){
            return;//user cancelled
        }
        String filePath = folder + file;
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(filePath));
            String line;
            
            //Clear previous data
            gtfData.clear();
            geneNames.clear();
            
            //Create table model
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Gene","Feature","Start","End","Strand"});
            
        while((line = br.readLine()) != null){
            //Skip comment lines
            if(line.startsWith("#")){
                continue;
            }
            //Split by TAB
            String[] parts = line.split("\t");
            
            //Check for nine Columns
            if(parts.length<9){
                continue;
            }
            //Extract fields
            String scaffold = parts[0]; 
            String feature = parts[2];
            String start = parts[3];
            String end = parts[4];
            String strand = parts[6];
            String attributes = parts[8];
            
            //Gene extration from Atributes
            String gene = null;
            

            // Case 1: attributes contains geneID= (transcript lines)
            if (attributes.contains("geneID=")) {
                gene = attributes.split("geneID=")[1].split("[;\\.]")[0];
            }

            // Case 2: attributes contains Parent= (exon/CDS lines)
            else if (attributes.contains("Parent=")) {
                gene = attributes.split("Parent=")[1].split("[;\\.]")[0];
                }
            if (gene == null || gene.isEmpty()) continue;
            
            //Maping gene to scaffold
            geneToScaffold.put(gene, scaffold);
            
            //Store each GTF rows
            gtfData.add(new String[]{gene, feature, start, end, strand});
            
            //Gene name to JCombobBox
            if (!geneNames.contains(gene)) {
                geneNames.add(gene);
                geneList.addItem(gene);
            } 
            
            //Add row to JTable
            model.addRow(new Object[]{gene, feature, start, end, strand});
        }
        
        gtfTable.setModel(model);

        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Error reading GTF file");
        }
        
        
    }//GEN-LAST:event_openGTFActionPerformed

    private void openFASTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFASTAActionPerformed
        //Load FASTA File 
        FileDialog dialog = new FileDialog(this, "Open FASTA File", FileDialog.LOAD);
        dialog.setVisible(true);

        String folder = dialog.getDirectory();
        String file = dialog.getFile();

        if (file == null) {
            return;
        }

        String filePath = folder + file;

        try {
            BufferedReader br = new BufferedReader(new FileReader(filePath));
            String line;

            fastaMap.clear();   // clear previous FASTA
            String currentHeader = "";
            StringBuffer seqBuffer = new StringBuffer();

            while ((line = br.readLine()) != null) {

                // If line starts with >, it's a new sequence header
                if (line.startsWith(">")) {

                    // Save previous sequence (if any)
                    if (!currentHeader.equals("")) {
                    fastaMap.put(currentHeader, seqBuffer.toString());
                    }

                    // Start a new sequence
                    currentHeader = line.substring(1).trim();  // remove >
                    seqBuffer = new StringBuffer();            // reset buffer
                }
                else {
                    seqBuffer.append(line.trim());
                }
            }

            // Save last sequence
            if (!currentHeader.equals("")) {
                fastaMap.put(currentHeader, seqBuffer.toString());
            }

            // Display: If only one sequence, show it
            if (fastaMap.size() == 1) {
                for (String key : fastaMap.keySet()) {
                genomeSequence = fastaMap.get(key);

                // Wrap the sequence for readability
                String wrapped = wrapSequence(genomeSequence, 200);

                fastaArea.setText(wrapped);
                }
            } else {
                fastaArea.setText("Loaded " + fastaMap.size() + " sequences.");
            }

        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error reading FASTA file.");
        }


        
    }//GEN-LAST:event_openFASTAActionPerformed

    private void ComputeStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeStatsButtonActionPerformed
        // Compute Statistics
        HashMap<String, Integer> exonCount = new HashMap<>();
        HashMap<String, Integer> geneStart = new HashMap<>();
        HashMap<String, Integer> geneEnd = new HashMap<>();
        
        int totalExonLength = 0;
        int totalExons = 0;

        for (String[] row : gtfData) {
            String gene = row[0];
            String feature = row[1];

            if (feature.equals("exon")) {
                int start = Integer.parseInt(row[2]);
                int end   = Integer.parseInt(row[3]);

                int length = end - start + 1;

                // total exon stats
                totalExonLength += length;
                totalExons++;

                // exon count per gene
                if (!exonCount.containsKey(gene)) {
                    exonCount.put(gene, 1);
                } else {
                    exonCount.put(gene, exonCount.get(gene) + 1);
                }

                // gene start
                if (!geneStart.containsKey(gene)) {
                    geneStart.put(gene, start);
                } else if (start < geneStart.get(gene)) {
                    geneStart.put(gene, start);
                }

                // gene end
                if (!geneEnd.containsKey(gene)) {
                    geneEnd.put(gene, end);
                } else if (end > geneEnd.get(gene)) {
                    geneEnd.put(gene, end);
                }
            }
        }
        
        //Average Exon length
        double avgExonLength = 0;
        
        if(totalExons > 0){
            avgExonLength = (double) totalExonLength / totalExons;
        }
        
        //Average Exon per gene
        double avgExonsPerGene = 0;

        for (String gene : exonCount.keySet()) {
            avgExonsPerGene += exonCount.get(gene);
        }

        if (exonCount.size() > 0) {
            avgExonsPerGene = avgExonsPerGene / exonCount.size();
        }
        
        //Longest and Shortest Gene
        int longestGene = 0;
        int shortestGene = Integer.MAX_VALUE;

        for (String gene : geneStart.keySet()) {
            int start = geneStart.get(gene);
            int end   = geneEnd.get(gene);

            int length = end - start + 1;

            if (length > longestGene) longestGene = length;
            if (length < shortestGene) shortestGene = length;
        }
        
        //Fasta Length
        int totalFastaLength = 0;
        int fastaCount = 0;

        for (String header : fastaMap.keySet()) {
            String seq = fastaMap.get(header);
            totalFastaLength += seq.length();
            fastaCount++;
        }

        double fastaLengthOutput = 0;

        if (fastaCount == 1) {
            // single-sequence FASTA
            fastaLengthOutput = totalFastaLength;
        } else if (fastaCount > 1) {
        // multi-sequence FASTA (average length)
        fastaLengthOutput = (double) totalFastaLength / fastaCount;
        }
        
        //Overall GC Content
        
        int totalGC = 0;

        for (String header : fastaMap.keySet()) {
            String seq = fastaMap.get(header);
            for (int i = 0; i < seq.length(); i++) {
                char c = seq.charAt(i);
                if (c == 'G' || c == 'C' || c == 'g' || c == 'c') {
                    totalGC++;
                }
            }
        }

        double gcPercentTotal = 0;

        if (totalFastaLength > 0) {
            gcPercentTotal = (double) totalGC / totalFastaLength * 100;
        }


        //Display all Stats
        String statsMessage =
        "=== GTF Statistics ===\n" +
        "Average Exon Length: " + String.format("%.2f", avgExonLength) + " bp\n" +
        "Average Exons per Gene: " + String.format("%.2f", avgExonsPerGene) + "\n" +
        "Longest Gene Length: " + longestGene + " bp\n" +
        "Shortest Gene Length: " + shortestGene + " bp\n\n" +

        "=== FASTA Statistics ===\n" +
        "FASTA Length (single) or Avg Length (multi): " + String.format("%.2f", fastaLengthOutput) + " bp\n" +
        "Overall GC Content: " + String.format("%.2f", gcPercentTotal) + "%";

        
        JOptionPane.showMessageDialog(this, statsMessage, "Genome Statistics", JOptionPane.INFORMATION_MESSAGE);




    }//GEN-LAST:event_ComputeStatsButtonActionPerformed

    private void HighlightExonsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighlightExonsButtonActionPerformed
    String gene = (String) geneList.getSelectedItem();
    if (gene == null) return;

    // Get scaffold
    String scaffold = geneToScaffold.get(gene);
    String seq = fastaMap.get(scaffold);
    if (fastaMap.isEmpty()) {
        fastaArea.setText("Please load a FASTA file first.");
    return;
    }

    if (seq == null) {
        fastaArea.setText("No FASTA sequence found for scaffold: " + scaffold);
        return;
    }

    // Find exons for selected gene
    ArrayList<int[]> exonList = new ArrayList<>();

    for (String[] row : gtfData) {
        if (row[0].equals(gene) && row[1].equals("exon")) {
            int start = Integer.parseInt(row[2]);
            int end   = Integer.parseInt(row[3]);
            exonList.add(new int[]{start, end});
        }
    }

    // Sort by position
    Collections.sort(exonList, (a, b) -> Integer.compare(a[0], b[0]));

    // Build highlighted text WITHOUT formatting first
    StringBuilder sb = new StringBuilder();
    int currentIndex = 0;

    for (int[] ex : exonList) {
        int start = ex[0] - 1;   // convert 1-based to 0-based
        int end   = ex[1];

        // Intron region
        sb.append(seq.substring(currentIndex, start).toLowerCase());

        // Mark exon using placeholders
        sb.append("<<<EXON_START>>>")
          .append(seq.substring(start, end).toUpperCase())
          .append("<<<EXON_END>>>");

        currentIndex = end;
    }

    // Add final region
    if (currentIndex < seq.length()) {
        sb.append(seq.substring(currentIndex).toLowerCase());
    }

    // Now apply formatting (style C)
    String formatted = sb.toString()
        .replace("<<<EXON_START>>>", "\n\n[[[")
        .replace("<<<EXON_END>>>", "]]]\n\n");

    // Wrap text to fixed width
    formatted = wrapSequence(formatted, 200);

    // Display
    fastaArea.setText(formatted);
    }//GEN-LAST:event_HighlightExonsButtonActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        String gene = (String) geneList.getSelectedItem();
        if (gene == null) return;

        // 1. Collect exon positions from GTF
        ArrayList<int[]> exons = new ArrayList<>();
        for (String[] row : gtfData) {
            if (row[0].equals(gene) && row[1].equals("exon")) {
                int start = Integer.parseInt(row[2]);
                int end   = Integer.parseInt(row[3]);
                exons.add(new int[]{start, end});
            }
        }
        if (fastaMap.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
        "Load FASTA before visualising gene.", 
        "Missing Data", 
        JOptionPane.WARNING_MESSAGE);
        return;
        }

        if (exons.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No exons found for this gene.");
        return;
        }

        // Sort exons by start
        Collections.sort(exons, (a,b) -> Integer.compare(a[0], b[0]));

        // 2. Determine gene region
        int geneStart = exons.get(0)[0];
        int geneEnd   = exons.get(exons.size() - 1)[1];

        // 3. Get the graphics context of the panel
        Graphics g = genePanel.getGraphics();

        // 4. Clear previous drawing
        g.clearRect(0, 0, genePanel.getWidth(), genePanel.getHeight());

        // Use 2D graphics
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(4));
        g2.setColor(Color.BLACK);

        int panelWidth  = genePanel.getWidth()  - 40; // margins
        int panelHeight = genePanel.getHeight();
        int midY = panelHeight / 2;

        // 5. Draw gene baseline
        g2.drawLine(20, midY, panelWidth + 20, midY);

        // 6. Scale base pairs to pixels
        double scale = panelWidth / (double)(geneEnd - geneStart);

        // 7. Draw exons as rectangles
        g2.setColor(Color.BLUE);

        for (int[] ex : exons) {
            int start = ex[0];
            int end   = ex[1];

            int x = 20 + (int)((start - geneStart) * scale);
            int width = (int)((end - start) * scale);

            g2.fillRect(x, midY - 15, width, 30);  // exon box
        }

    }//GEN-LAST:event_drawButtonActionPerformed

    private void geneListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geneListActionPerformed
        String gene = (String) geneList.getSelectedItem();

        if (gene == null) return;  // safety check

        // Find which scaffold this gene belongs to
        String scaffold = geneToScaffold.get(gene);

        // Fetch the correct FASTA sequence from the HashMap
        String seq = fastaMap.get(scaffold);

        if (seq != null) {
            genomeSequence = seq;  // store for highlighting later
    
            // Wrap lines (200 bases per line)
            String wrapped = wrapSequence(seq, 200);
            fastaArea.setText(wrapped);
        } else {
        fastaArea.setText("No FASTA sequence found for scaffold: " + scaffold);
        }

        
    }//GEN-LAST:event_geneListActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComputeStatsButton;
    private javax.swing.JButton HighlightExonsButton;
    private javax.swing.JButton drawButton;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JTextArea fastaArea;
    private javax.swing.JComboBox<String> geneList;
    private javax.swing.JPanel genePanel;
    private javax.swing.JTable gtfTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem openFASTA;
    private javax.swing.JMenuItem openGTF;
    // End of variables declaration//GEN-END:variables
}
